# Generated by Django 5.2.17 on 2026-10-02 06:12

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Unsupported image format. Upload a JPEG, PNG or WebP file.'), accounts.models.validate_profile_image_size], verbose_name='profile image'),
        ),
    ]
