"""
Django settings for ServiGo project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import dj_database_url
import whitenoise

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Define and initialise environment variables
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1', 'testserver']),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_PORT=(int, 587),
)
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "testserver"])


# Application definition

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "crispy_forms",
    "crispy_bootstrap5",
    "django_browser_reload",
    "rest_framework",
    "corsheaders",
    "drf_spectacular",

    # Local apps
    "accounts",
    "services",
    "bookings",
    "ev_charging",
    "feedback",
    "dashboard",
    "core",
    "api",
]

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Straight after SecurityMiddleware, which is where WhiteNoise's docs put
    # it: it serves the compiled staticfiles from its own middleware and needs
    # to sit above anything that could short-circuit a request, so a 404 for a
    # missing asset is still answered by gunicorn rather than by the proxy.
    # Without this, DEBUG=False serves no CSS or JS at all — Django's static
    # view only answers requests when DEBUG is on.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Resets the rate-limiter cache between tests — see the module docstring in
# config/test_runner.py for why that is not optional once throttling is on.
TEST_RUNNER = "config.test_runner.ServiGoTestRunner"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves STATIC_ROOT directly and caches it under a hashed filename,
# so a deploy is atomic: the old bundle keeps answering until the new one is
# complete. `CompressedManifestStaticFilesStorage` additionally rewrites every
# {% static %} reference to its hashed name, which is what stops a browser
# from holding on to the previous deploy's CSS. It requires collectstatic to
# have run, so it is only switched on outside DEBUG — a developer running
# `runserver` reads straight from STATICFILES_DIRS and needs neither.
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# ── Media storage ────────────────────────────────────────────────────────────
# Locally uploads land in MEDIA_ROOT. On Render the same models write to
# Cloudinary, so set CLOUDINARY_URL (or CLOUDINARY_CLOUD_NAME) in the
# environment and every ImageField/FileField is transparently offloaded.
CLOUDINARY_URL = env("CLOUDINARY_URL", default="")
CLOUDINARY_CLOUD_NAME = env("CLOUDINARY_CLOUD_NAME", default="")

if CLOUDINARY_CLOUD_NAME or CLOUDINARY_URL:
    INSTALLED_APPS += [
        "cloudinary_storage",
        "cloudinary",
    ]
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard:customer"
LOGOUT_REDIRECT_URL = "core:home"

# Session settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True

# Email configuration
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
SERVER_EMAIL = env("SERVER_EMAIL", default=EMAIL_HOST_USER)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=SERVER_EMAIL)

# Security settings for production
#
# `SECURE_PROXY_SSL_HEADER` is what makes the three below work at all behind
# Render. Without it Django sees the request as plain http:// (the proxy
# terminated TLS and reconnected over http), so SECURE_SSL_REDIRECT redirects
# every page to https://… in a loop and SESSION_COOKIE_SECURE / CSRF_COOKIE_
# SECURE refuse to set the cookies at all. Trusting the header is safe only
# because Render strips any client-supplied X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# Authentication backends: accept email OR username at login
AUTHENTICATION_BACKENDS = ["accounts.backends.EmailOrUsernameBackend"]

# Caching
#
# The login/registration rate limiter and DRF's throttles both count against the
# default cache, so it has to be one the whole application agrees on. LocMem is
# per-process and resets on every restart, which is fine for the single gunicorn
# worker a free Render service runs and would be wrong for anything larger —
# swap in Redis before scaling out, or the limits become per-worker and a
# multi-worker deploy is effectively unthrottled.
CACHES = {
    "default": {
        "BACKEND": env(
            "CACHE_BACKEND",
            default="django.core.cache.backends.locmem.LocMemCache",
        ),
        "LOCATION": "unique-snowflake",
    }
}

# ── HTML auth rate limiting ───────────────────────────────────────────────────
# The REST API is throttled by DRF; these two views render HTML and so sit
# outside that machinery entirely. Without their own limiter the login form is
# the one endpoint a password-guessing run can hammer freely, which is why
# `accounts.views` applies the same counter by hand.
LOGIN_RATE_LIMIT = env.int("LOGIN_RATE_LIMIT", default=10)
LOGIN_RATE_WINDOW_SECONDS = env.int("LOGIN_RATE_WINDOW_SECONDS", default=300)
REGISTER_RATE_LIMIT = env.int("REGISTER_RATE_LIMIT", default=5)
REGISTER_RATE_WINDOW_SECONDS = env.int(
    "REGISTER_RATE_WINDOW_SECONDS", default=3600
)

# Messages framework
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# ServiGo specific settings
SERVIGO_SITE_NAME = "ServiGo"
SERVIGO_SITE_TAGLINE = "Your trusted home services partner"

# ── CORS ─────────────────────────────────────────────────────────────────────
# The Next.js frontend runs on a different origin, so every origin it may be
# served from has to be allowed explicitly — except Render/Vercel preview
# deploys, whose hostnames are not known ahead of time. Those are matched by
# the regexes below rather than by `*`, which django-cors-headers refuses.
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:3000", "http://127.0.0.1:3000"],
)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.onrender\.com$",
    r"^https://.*\.vercel\.app$",
]

# ── Django REST Framework ─────────────────────────────────────────────────────
#
# Throttles are deliberately on by default rather than opt-in per view: the
# endpoints worth rate limiting are the ones that authenticate (`/api/auth/
# login/`, `/api/auth/register/`), and a view-level omission is the kind of
# thing that only shows up as a brute-force success after the fact. A view that
# legitimately needs to be unbounded sets `throttle_classes = []` explicitly,
# which is a visible decision rather than a silent one.
#
# Anonymous callers are held to the tighter budget because they are the ones a
# credential-stuffing run comes from — 20 a minute is generous for reading the
# public catalogue and useless for trying thousands of passwords. Authenticated
# callers get more headroom because a signed-in customer browsing their own
# bookings issues a burst of requests by design.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": env("ANON_THROTTLE_RATE", default="20/min"),
        "user": env("USER_THROTTLE_RATE", default="60/min"),
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ── drf-spectacular (OpenAPI / Swagger) ───────────────────────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE": "ServiGo API",
    "DESCRIPTION": "REST API for the ServiGo home-services platform.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # By default spectacular lists every read-only field in the schema's
    # `required` array. For a response that is correct per OpenAPI — a
    # read-only property in `required` means "required on the way out only" —
    # but those same components are reused as request bodies, where it
    # advertises "you must send role" for a field the endpoint ignores.
    # Turning it off keeps generated clients from demanding server-owned
    # fields (e.g. RegisterSerializer's `role` / `is_staff`).
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    # Both `bookings.Booking.status` and `ev_charging.EVChargingBooking.status`
    # are a field called "status" over a different TextChoices set, which
    # spectacular can only disambiguate with a hash suffix ("Status528Enum").
    # Naming them here keeps the generated schema stable across unrelated
    # changes and — more importantly — stops a service-booking status from
    # ever being sent where an EV reservation status is expected.
    "ENUM_NAME_OVERRIDES": {
        "BookingStatusEnum": "bookings.models.Booking.Status",
        "EVBookingStatusEnum": "ev_charging.models.EVChargingBooking.Status",
        "EVStationStatusEnum": "ev_charging.models.EVChargingStation.Status",
        "EVChargerTypeEnum": "ev_charging.models.EVChargingStation.ChargerType",
    },
}