# Generated by Django 5.2.17 on 2026-09-29 06:08

from django.db import migrations, models


#: How each retired status maps onto the six-milestone lifecycle.
#:
#: The old enum had `confirmed` covering both "a technician has been handed the
#: job" and "the technician confirmed they will take it", and `on_site` for
#: arrival. The new enum splits the first into `claimed` and `accepted`, so
#: neither old value has a one-to-one successor:
#:
#:   confirmed → claimed    a confirmed booking had a technician assigned to it,
#:                          which is exactly what claiming now records. Nothing
#:                          can distinguish the two from stored data, so every
#:                          one lands on the earlier of the two new stages —
#:                          the one that is provably true. A technician can walk
#:                          it forward with "Accept Job"; the alternative would
#:                          be to assert a dispatch acceptance that never
#:                          happened.
#:   on_site   → arrived    a rename with no semantic change at all.
#:
#: Rows already `pending`, `in_progress`, `completed` or `cancelled` are left
#: alone — those values are unchanged in the new enum.
FORWARD_STATUS_MAP = {
    "confirmed": "claimed",
    "on_site": "arrived",
}

#: The inverse. Two new statuses collapse back onto `confirmed` for the same
#: reason they were split apart, and `arrived` reverses to `on_site`.
REVERSE_STATUS_MAP = {
    "claimed": "confirmed",
    "accepted": "confirmed",
    "arrived": "on_site",
}


def remap_statuses(apps, schema_editor, status_map):
    """
    Move every booking off a retired status value.

    Uses `.update()` rather than the model so this stays a one-statement
    migration: it runs against the historical model, whose `Status` enum no
    longer lists the old values, and it deliberately does not fire `save()` or
    `auto_now` — only the status column is changing.
    """
    Booking = apps.get_model("bookings", "Booking")
    for old, new in status_map.items():
        Booking.objects.filter(status=old).update(status=new)


def forwards(apps, schema_editor):
    remap_statuses(apps, schema_editor, FORWARD_STATUS_MAP)


def backwards(apps, schema_editor):
    remap_statuses(apps, schema_editor, REVERSE_STATUS_MAP)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('accepted', 'Accepted'), ('arrived', 'Technician arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status'),
        ),
        # The AlterField above only rewrites the column's declared choices —
        # there is no database-level enum to alter — so the data move has to be
        # its own operation. It runs after it so the column's default and
        # choices already match the new lifecycle by the time any row is read.
        migrations.RunPython(forwards, backwards),
    ]
