# Generated by Django 5.2.17 on 2026-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_charging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evchargingbooking',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Registration plate of the vehicle being charged', max_length=32, verbose_name='vehicle number'),
        ),
    ]
